---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-registry-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: strimzi-registry-operator
rules:

  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get]

  # Kopf: posting the events about the handlers progress/errors.
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [roundtable.lsst.codes]
    resources: [strimzischemaregistries]
    verbs: [get, list, watch, patch]

  # Access to the built-in resources the operator manages
  - apiGroups: [""]
    resources: [secrets, configmaps, services]
    verbs: [get, list, watch, patch, create]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: [get, list, watch, patch, create]

  # Access to the KafkaUser resource
  - apiGroups: [kafka.strimzi.io]
    resources: [kafkausers, kafkas]
    verbs: [list, get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-registry-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: strimzi-registry-operator
subjects:
  - kind: ServiceAccount
    name: strimzi-registry-operator
